
//========================
//マクロ定義
//========================
#define DASH_EXTENSION		(15)				//ダッシュコマンドの入力猶予
#define HADOUKEN			(10)			//波動拳コマンドの入力猶予
#define TATUMAKI			(10)			//竜巻旋風脚コマンドの入力猶予
#define SYOURYUKEN			(10)			//昇竜拳コマンドの入力猶予

//コマンド用ビット(実装するかは不明)
//操作されているとき
//レバー
#define INPUT1	(0x1)					//左下
#define INPUT2	(0x2)					//下
#define INPUT3	(0x4)					//右下
#define INPUT4	(0x8)					//左
#define INPUT5	(0x10)					//ニュートラル
#define INPUT6	(0x20)					//右
#define INPUT7	(0x40)					//左上
#define INPUT8	(0x80)					//上
#define INPUT9	(0x100)					//右上

//攻撃
#define INPUT_LATK	(0x200)				//弱攻撃
#define INPUT_MATK	(0x400)				//中攻撃
#define INPUT_HATK	(0x800)				//強攻撃

//操作されていないとき
//レバー
#define INPUT_NOT1		(0x1000)		//左下
#define INPUT_NOT2		(0x2000)		//下
#define INPUT_NOT3		(0x4000)		//右下
#define INPUT_NOT4		(0x8000)		//左
#define INPUT_NOT5		(0x10000)		//レバーがニュートラル
#define INPUT_NOT6		(0x20000)		//右
#define INPUT_NOT7		(0x40000)		//左上
#define INPUT_NOT8		(0x80000)		//上
#define INPUT_NOT9		(0x100000)		//右上

//攻撃
#define INPUT_NOT_LATK	(0x200000)		//弱攻撃
#define INPUT_NOT_MATK	(0x400000)		//中攻撃
#define INPUT_NOT_HATK	(0x800000)		//強攻撃

#define INPUT_NULL		(0x4000000)		//どこも押していない状態
#define INPUT_END		(0x8000000)		//コマンドの末尾

static const int
//前ダッシュ
CMD66[] = { INPUT_NOT6 | INPUT_NOT4 , INPUT6 | INPUT_NOT4 , INPUT_NOT6 | INPUT_NOT4 , INPUT6 | INPUT_NOT4 ,INPUT_END | DASH_EXTENSION },

CMD44[] = { INPUT_NOT4 | INPUT_NOT6 , INPUT4 | INPUT_NOT6 , INPUT_NOT4 | INPUT_NOT6 , INPUT4 | INPUT_NOT6 ,INPUT_END | DASH_EXTENSION },

//波動
CMD236L[] = { INPUT2 | INPUT_NOT3 | INPUT_NOT_LATK,INPUT3 | INPUT_NOT_LATK,INPUT_NOT3 | INPUT6,INPUT_LATK,INPUT_END | HADOUKEN },
CMD236M[] = { INPUT2 | INPUT_NOT3 | INPUT_NOT_MATK,INPUT3 | INPUT_NOT_MATK,INPUT_NOT3 | INPUT6,INPUT_MATK,INPUT_END | HADOUKEN },
CMD236H[] = { INPUT2 | INPUT_NOT3 | INPUT_NOT_HATK,INPUT3 | INPUT_NOT_HATK,INPUT_NOT3 | INPUT6,INPUT_HATK,INPUT_END | HADOUKEN },

//竜巻
CMD214L[] = { INPUT2 | INPUT_NOT1 | INPUT_NOT_LATK,INPUT1 | INPUT_NOT_LATK,INPUT_NOT1 | INPUT4,INPUT_LATK,INPUT_END | TATUMAKI },
CMD214M[] = { INPUT2 | INPUT_NOT1 | INPUT_NOT_MATK,INPUT1 | INPUT_NOT_MATK,INPUT_NOT1 | INPUT4,INPUT_MATK,INPUT_END | TATUMAKI },
CMD214H[] = { INPUT2 | INPUT_NOT1 | INPUT_NOT_HATK,INPUT1 | INPUT_NOT_HATK,INPUT_NOT1 | INPUT4,INPUT_HATK,INPUT_END | TATUMAKI },

//昇竜
CMD623L[] = { INPUT6 | INPUT_NOT_LATK,INPUT2 | INPUT_NOT3 | INPUT_NOT_LATK,INPUT3 | INPUT_NOT_LATK,INPUT_LATK,INPUT_END | SYOURYUKEN },
CMD623M[] = { INPUT6 | INPUT_NOT_MATK,INPUT2 | INPUT_NOT3 | INPUT_NOT_MATK,INPUT3 | INPUT_NOT_MATK,INPUT_MATK,INPUT_END | SYOURYUKEN },
CMD623H[] = { INPUT6 | INPUT_NOT_HATK,INPUT2 | INPUT_NOT3 | INPUT_NOT_HATK,INPUT3 | INPUT_NOT_HATK,INPUT_HATK,INPUT_END | SYOURYUKEN },

//昇竜
CMD421L[] = { INPUT4 | INPUT_NOT_LATK,INPUT2 | INPUT_NOT1 | INPUT_NOT_LATK,INPUT1 | INPUT_NOT_LATK,INPUT_LATK,INPUT_END | SYOURYUKEN },
CMD421M[] = { INPUT4 | INPUT_NOT_MATK,INPUT2 | INPUT_NOT1 | INPUT_NOT_MATK,INPUT1 | INPUT_NOT_MATK,INPUT_MATK,INPUT_END | SYOURYUKEN },
CMD421H[] = { INPUT4 | INPUT_NOT_HATK,INPUT2 | INPUT_NOT1 | INPUT_NOT_HATK,INPUT1 | INPUT_NOT_HATK,INPUT_HATK,INPUT_END | SYOURYUKEN };

